### ISSUE TITLE
Suggestion : set Users's Settings

### ISSUE THREAD

**Issue by AEK-BKF** [oriceon/laravel-settings#1]
Hi man,
Thank you so much for this nice package,
I suggest you to set a method to set a given user settings, to allow each user his proper settings.
exp : 
$user->settings->set('key', 'value');
$user->settings->get('key1');
 
Good luck :)

**Comment by oriceon** [comment]
Thanks, i`ll take into the consideration.

**Comment by codetheorist** [comment]
I don't believe this should be a feature, as it would add too much excess code that would be unwarranted. 

The current system works fine for me with per-user settings. I simply use the user ID as the first key, or site if it is a global setting. Then it's simply a case of checking whether the user has their own key and if so, do they have a sub-key for this setting. If they don't fallback to global.
